// [claude-code 2026-02-26] Shared change log for multi-agent coordination.

export type ChangelogEntry = {
  date: string;
  agent: 'claude-code' | string;
  summary: string;
  files: string[];
};

export const changelog: ChangelogEntry[] = [
  {
    date: '2026-03-11T22:00:00',
    agent: 'claude-code',
    summary: 'Phase 7: Agent performance auto-recording (polymarket-tracker, outcome-tracker, /api/agents/performance endpoint). IV Score persistence — runs as background ticker (60s), events use 7-day window (never restart decay), score cached to DB across restarts. RiskFlow 24h stalemate rule — items older than 24h filtered out on init. VIX spike popup replaced with pulsating border (red >22, orange 16-22, yellow 14-16). Frontend AgentPerformanceTab wired to combined futures+prediction performance data.',
    files: [
      'backend-hono/src/services/agents/polymarket-tracker.ts',
      'backend-hono/src/services/agents/outcome-tracker.ts',
      'backend-hono/src/services/market-data/iv-score-ticker.ts',
      'backend-hono/src/routes/agents/handlers.ts',
      'backend-hono/src/routes/agents/index.ts',
      'backend-hono/src/routes/market-data/handlers.ts',
      'backend-hono/src/index.ts',
      'backend-hono/migrations/010_polymarket_predictions.sql',
      'frontend/components/IVScoreCard.tsx',
      'frontend/components/journal/AgentPerformanceTab.tsx',
      'frontend/contexts/RiskFlowContext.tsx',
      'frontend/lib/services.ts',
    ],
  },
  {
    date: '2026-03-12T09:00:00',
    agent: 'claude-code',
    summary: 'RiskFlow full-feed overhaul: replaced source text with X/Notion SVG logos, removed Neutral bias display, right-justified cyclical/counter-cyclical badges, fixed point scoring (severity × tag multiplier). VIX spike notice shows once per session via sessionStorage. Removed floating VIX ticker in combined panels layout. Fixed Brief refresh button. Reverted all calendars (Dashboard, Mission Control, full tab) to TradingView widget embeds — reliable data, TV-style layout.',
    files: [
      'frontend/components/feed/NewsSection.tsx',
      'frontend/components/IVScoreCard.tsx',
      'frontend/components/layout/MainLayout.tsx',
      'frontend/components/mission-control/BriefMiniWidget.tsx',
      'frontend/components/executive/SessionCalendarList.tsx',
      'frontend/components/mission-control/SessionCalendarMini.tsx',
      'frontend/components/econ/EconCalendar.tsx',
    ],
  },
  {
    date: '2026-03-12T06:00:00',
    agent: 'claude-code',
    summary: 'Regime Tracker: W/L→ORB bullish/bearish days, AI Generate CTA (opens chat with regimes skill), delete any regime, 12H NY time, active regimes shown in collapsed categories. Brief widget: scrollable full reports, AI generate button, comprehensive MDB/TOTT prompts (400-600w / 600-1000w), short ADB/PMDB. Added regimes skill to registry.',
    files: [
      'frontend/lib/regimes.ts',
      'frontend/lib/regime-store.ts',
      'frontend/lib/regime-time.ts',
      'frontend/lib/skills.ts',
      'frontend/lib/skillPrefixes.ts',
      'frontend/components/regimes/RegimeTrackerModal.tsx',
      'frontend/components/mission-control/RegimeMini.tsx',
      'frontend/components/mission-control/BriefMiniWidget.tsx',
      'frontend/components/dashboard/RegimeCard.tsx',
      'frontend/components/ChatInterface.tsx',
      'frontend/components/layout/MainLayout.tsx',
      'backend-hono/src/routes/notion/index.ts',
    ],
  },
  {
    date: '2026-03-12T04:30:00',
    agent: 'claude-code',
    summary: 'IV scoring overhaul: VIX 24→score 9 (blended ~7), stubborn below VIX 16 (75/25 weights), VIX floor prevents dilution, geopolitical weight boosted 8→9, scoreToPoints steeper curve, Boardroom tab hidden.',
    files: [
      'backend-hono/src/services/market-data/iv-scorer.ts',
      'backend-hono/src/services/analysis/iv-scorer.ts',
      'frontend/components/layout/NavSidebar.tsx',
    ],
  },
  {
    date: '2026-03-12T03:00:00',
    agent: 'claude-code',
    summary: 'Comprehensive onboarding: SetupGuideCard with status indicators on Dashboard, SETUP.md handoff guide, chat suggestion chips wired to skill system (mdb_report, tott, psych_eval, blindspots), configurable OpenClaw gateway port in Settings.',
    files: [
      'SETUP.md',
      'frontend/components/onboarding/SetupGuideCard.tsx',
      'frontend/components/executive/ExecutiveDashboard.tsx',
      'frontend/lib/skills.ts',
      'frontend/lib/skillPrefixes.ts',
      'frontend/components/chat/ChatGreeting.tsx',
      'frontend/components/chat/PulseThread.tsx',
      'frontend/components/ChatInterface.tsx',
      'frontend/contexts/SettingsContext.tsx',
      'frontend/contexts/GatewayContext.tsx',
      'frontend/components/SettingsPanel.tsx',
    ],
  },
  {
    date: '2026-03-12T01:00:00',
    agent: 'claude-code',
    summary: 'Replace TradingView iframe calendar (X-Frame-Options blocked) with native EconCalendar: week picker, day tabs with beat/miss summaries, time-block grouping (Pre-Market/Session/After Hours), P/A/F column headers, importance filter, refresh button, EconTickerFooter. SessionCalendarList and SessionCalendarMini also replaced with native rendering using backend econ data. RiskFlow source icons (X/Notion SVGs), Tape→RiskFlow unification, Brief refresh + mini widget, agent-controllable BlindspotsWidget.',
    files: [
      'frontend/components/econ/EconCalendar.tsx',
      'frontend/components/executive/SessionCalendarList.tsx',
      'frontend/components/mission-control/SessionCalendarMini.tsx',
      'frontend/components/RiskFlowPanel.tsx',
      'frontend/components/feed/CompactRiskFlowCard.tsx',
      'frontend/components/executive/ExpandableTapeItem.tsx',
      'frontend/components/executive/ExecutiveDashboard.tsx',
      'frontend/components/mission-control/BriefMiniWidget.tsx',
      'frontend/components/mission-control/BlindspotsWidget.tsx',
      'frontend/lib/layoutOrderStorage.ts',
      'frontend/lib/services.ts',
      'backend-hono/src/routes/blindspots.ts',
    ],
  },
  {
    date: '2026-03-11T23:30:00',
    agent: 'claude-code',
    summary: 'Track 6 v7.7.7: TradingView-style session calendar redesign — EconCalendar.tsx gets P/A/F column headers on day groups. EconEventRow.tsx replaces importance dots with volume bars (height=importance 1-3), adds beat/miss indicators (green Check / red X via lucide), reorders columns to P/A/F, more row spacing. SessionCalendarList.tsx gets P/A/F headers + beat/miss check/X per event row. EconTickerFooter.tsx appends BEAT/MISS inline text with checkmark/X unicode to ticker insights.',
    files: [
      'frontend/components/econ/EconCalendar.tsx',
      'frontend/components/econ/EconEventRow.tsx',
      'frontend/components/econ/EconTickerFooter.tsx',
      'frontend/components/executive/SessionCalendarList.tsx',
    ],
  },
  {
    date: '2026-03-11T22:00:00',
    agent: 'claude-code',
    summary: 'Track 7 v7.7.7: 7A — TradingJournal.tsx with Human/Agent toggle tabs (HumanPsychTab: ER trend sparkline, infractions, discipline gauge + notes; AgentPerformanceTab: proposal tracker, win rate, R:R KPIs, expandable per-day proposals). Backend /api/journal/ routes (entries CRUD + summary). 7B — ER Monitor upgrade: VAD trigger replaces browser Speech API, Whisper-on-demand via POST /api/voice/analyze-sentiment (transcribe + Claude Haiku sentiment), escalating interventions (visual ER<-1, voice TTS ER<-3, lockout UI ER<-5)',
    files: [
      'frontend/components/journal/TradingJournal.tsx',
      'frontend/components/journal/HumanPsychTab.tsx',
      'frontend/components/journal/AgentPerformanceTab.tsx',
      'frontend/lib/services.ts',
      'frontend/contexts/ERContext.tsx',
      'frontend/components/mission-control/EmotionalResonanceMonitor.tsx',
      'backend-hono/src/services/journal-service.ts',
      'backend-hono/src/routes/journal/index.ts',
      'backend-hono/src/routes/journal/handlers.ts',
      'backend-hono/src/services/voice-sentiment.ts',
      'backend-hono/src/routes/voice/index.ts',
      'backend-hono/src/routes/voice/handlers.ts',
      'backend-hono/src/routes/index.ts',
    ],
  },
  {
    date: '2026-03-11T18:00:00',
    agent: 'claude-code',
    summary: 'Track 5 v7.7.7: Chat + toolbar — removed steer strip from PulseComposer/PromptBox (always full input), added queue chips (max 2) with cancel, added /stop to PulseSlashPicker, power button always visible in TopHeader (dim when inactive), RiskFlow drag-drop into chat (application/x-riskflow), created useVoiceMemory.ts hook (mic device persistence + transcript history), added mic device selector to SettingsPanel notifications tab',
    files: [
      'frontend/components/chat/PulseComposer.tsx',
      'frontend/components/ui/chatgpt-prompt-input.tsx',
      'frontend/components/chat/PulseSlashPicker.tsx',
      'frontend/lib/skills.ts',
      'frontend/components/layout/TopHeader.tsx',
      'frontend/components/RiskFlowPanel.tsx',
      'frontend/hooks/useVoiceMemory.ts',
      'frontend/components/SettingsPanel.tsx',
    ],
  },
  {
    date: '2026-03-11T16:00:00',
    agent: 'claude-code',
    summary: 'Track 3 v7.7.7: RiskFlow card overhaul — removed Neutral text, added X/Notion/MW SVG source logos, moved cyclical badge top-right, added point range display, approve/deny CTA on proposals, chat CTA on news alerts, onChatAlert prop on panel, extended RiskFlowAlert type with pointRange/direction/cyclical/instrument/authorHandle, wired PriceBrainScore from backend context, created CompactRiskFlowCard.tsx with minimal (2-line) and mini (single-line ticker-tape) variants',
    files: [
      'frontend/lib/riskflow-feed.ts',
      'frontend/contexts/RiskFlowContext.tsx',
      'frontend/components/RiskFlowPanel.tsx',
      'frontend/components/CompactRiskFlowCard.tsx',
    ],
  },
  {
    date: '2026-03-11T14:00:00',
    agent: 'claude-code',
    summary: 'Track 2: Wire frontend to backend IV score — IVScoreResponse type, getIVScore() on MarketDataService, IVScoreCard redesigned with point range + rationale tooltip + environment label, TopHeader/MainLayout/FloatingWidget/MiniWidget switched from quickIVScore(vix) to backend.marketData.getIVScore(), deleted hardcoded INSTRUMENT_CONFIG, NewsFeed uses inline IV badge',
    files: [
      'frontend/types/market-data.ts',
      'frontend/lib/services.ts',
      'frontend/components/IVScoreCard.tsx',
      'frontend/components/layout/TopHeader.tsx',
      'frontend/components/layout/MainLayout.tsx',
      'frontend/components/layout/FloatingWidget.tsx',
      'frontend/mini-widget-entry.tsx',
      'frontend/components/NewsFeed.tsx',
    ],
  },
  {
    date: '2026-03-11T12:00:00',
    agent: 'claude-code',
    summary: 'Track 4: Mission Control overhaul — removed Panels header, moved collapse into MC KanbanTitle header, 560px fixed→flex-1 for 50/50 MC/Tape split, added calendar to MissionWidgetId, replaced drag-drop with gear WidgetArrangeMenu (up/down + visibility toggle), created SessionCalendarMini (P/A/F columns, max 4 events, beat/miss dots)',
    files: [
      'frontend/components/layout/MainLayout.tsx',
      'frontend/lib/layoutOrderStorage.ts',
      'frontend/components/mission-control/SessionCalendarMini.tsx',
      'frontend/components/mission-control/WidgetArrangeMenu.tsx',
    ],
  },
  {
    date: '2026-03-11T09:00:00',
    agent: 'claude-code',
    summary: 'Track 8: BoardroomView popup interception via window message listener → window.open in new tab; ExecutiveDashboard getBriefLabel returns Tale of the Tape on Sunday + Monday<7AM, show only items[0].detail instead of joining multiple',
    files: [
      'frontend/components/BoardroomView.tsx',
      'frontend/components/executive/ExecutiveDashboard.tsx',
    ],
  },
  {
    date: '2026-03-11T06:00:00',
    agent: 'claude-code',
    summary: 'Track 1: Backend services — GET /api/market-data/iv-score (blended 60/40 VIX+headlines), iv-scorer.ts + point-estimator.ts services, classification fix (Senate→commentary, CPI→econ with strict word-boundary gates), briefing→single item + TOTT type, RiskFlow prints merged into schedule endpoint',
    files: [
      'backend-hono/src/services/market-data/iv-scorer.ts',
      'backend-hono/src/services/market-data/point-estimator.ts',
      'backend-hono/src/services/iv-scoring-v2.ts',
      'backend-hono/src/routes/market-data/handlers.ts',
      'backend-hono/src/routes/market-data/index.ts',
      'backend-hono/src/services/notion-service.ts',
      'backend-hono/src/routes/notion/index.ts',
    ],
  },
  {
    date: '2026-03-11T03:30:00',
    agent: 'claude-code',
    summary: 'Track 4: Chat Rebuild — PromptBox (unified input with vanish animation, image dialog, Think Harder sparkle toggle, mic button, compact mode), PulseComposer rewired to PromptBox + API skills fetch, PulseThread enhanced (hover action bar with Copy/Checkpoint, scroll-to-bottom IntersectionObserver, ChainOfThought gold-bordered display, fadeSlideIn animation), ChatInterface simplified, AskHarpChatPanel aligned to PulseComposer, PulseFloatingChat migrated from useChatSession to useOpenClawRuntime + AssistantRuntimeProvider + PulseThread compact',
    files: [
      'frontend/components/ui/chatgpt-prompt-input.tsx',
      'frontend/components/chat/PulseComposer.tsx',
      'frontend/components/chat/PulseThread.tsx',
      'frontend/components/ChatInterface.tsx',
      'frontend/components/chat/AskHarpChatPanel.tsx',
      'frontend/components/chat/PulseFloatingChat.tsx',
      'frontend/index.css',
    ],
  },
  {
    date: '2026-03-11T03:00:00',
    agent: 'claude-code',
    summary: 'Track 5: Claude SDK Bridge + 21st API fallback — zero-cost Opus inference via Max subscription CLI bridge (process-manager, bridge relay, stream-json parser), 21st API deep thinking fallback service + token proxy route, claude-local model key in ai-config, 4-tier inference priority chain in chat handler (OpenClaw → Claude SDK → 21st API → OpenRouter)',
    files: [
      'backend-hono/src/services/claude-sdk/process-manager.ts',
      'backend-hono/src/services/claude-sdk/bridge.ts',
      'backend-hono/src/services/twenty-first/deep-think.ts',
      'backend-hono/src/routes/twenty-first/index.ts',
      'backend-hono/src/routes/ai/handlers/chat.ts',
      'backend-hono/src/config/ai-config.ts',
      'backend-hono/src/types/ai-types.ts',
      'backend-hono/src/routes/index.ts',
      'backend-hono/src/index.ts',
      'backend-hono/.env',
    ],
  },
  {
    date: '2026-03-11T02:00:00',
    agent: 'claude-code',
    summary: 'Track 3: Backend context + preferences — conversation store upgrade (50 msg, token estimation, auto-summarization via OpenClaw), agent-instructions.ts (dynamic prompts, skill injection, 5min cache), skills endpoint GET /api/ai/skills, file attachment support (images/text/code/PDF), user settings persistence (PostgreSQL + localStorage sync), AI config updates',
    files: [
      'backend-hono/src/services/ai/conversation-store.ts',
      'backend-hono/src/services/ai/agent-instructions.ts',
      'backend-hono/src/services/openclaw-handler.ts',
      'backend-hono/src/routes/ai/handlers/skills.ts',
      'backend-hono/src/routes/ai/index.ts',
      'backend-hono/src/routes/ai/handlers/chat.ts',
      'backend-hono/src/services/settings-store.ts',
      'backend-hono/src/routes/settings/index.ts',
      'backend-hono/src/routes/index.ts',
      'backend-hono/src/config/ai-config.ts',
      'frontend/contexts/SettingsContext.tsx',
    ],
  },
  {
    date: '2026-03-11T01:00:00',
    agent: 'claude-code',
    summary: 'Track 2: Liquid Glass + New UI Components — created GlassEffect/GlassDock/GlassButton/GlassFilter, AiLoader, AnimatedText (useAnimatedText hook), AgentPlan (expand/collapse), VanishInput (canvas particle animation), Conversation (scroll-to-bottom + IntersectionObserver), Message primitives, Actions + AiActions (Copy/Retry/Like/Dislike)',
    files: [
      'frontend/components/ui/liquid-glass.tsx',
      'frontend/components/ui/ai-loader.tsx',
      'frontend/components/ui/animated-text.tsx',
      'frontend/components/ui/agent-plan.tsx',
      'frontend/components/ui/placeholders-and-vanish-input.tsx',
      'frontend/components/ui/conversation.tsx',
      'frontend/components/ui/message.tsx',
      'frontend/components/ui/actions.tsx',
      'frontend/components/ui/ai-actions.tsx',
    ],
  },
  {
    date: '2026-03-11T00:30:00',
    agent: 'claude-code',
    summary: 'Track 1 Foundation: installed framer-motion/clsx/tailwind-merge, created cn() utility, replaced ~800 hardcoded hex colors with CSS variables across 90+ files, updated Button.tsx variants, created Card/Tooltip/Avatar UI primitives, added moveBackground/fadeSlideIn keyframes',
    files: [
      'frontend/lib/utils.ts',
      'frontend/components/ui/Button.tsx',
      'frontend/components/ui/card.tsx',
      'frontend/components/ui/tooltip.tsx',
      'frontend/components/ui/avatar.tsx',
      'frontend/index.css',
    ],
  },
  {
    date: '2026-03-10T23:30:00',
    agent: 'claude-code',
    summary: 'Burst polling (5s for 30s on econ releases), actual extraction from FJ tweets → Notion calendar + prints DB, NickTimiraos as trusted X source, InsiderWire source mapping fix',
    files: [
      'backend-hono/src/services/twitter-cli/econ-triggered-poller.ts',
    ],
  },
  {
    date: '2026-03-10T22:00:00',
    agent: 'claude-code',
    summary: 'T3 remaining fixes: highCount includes critical alerts, priorityFilter=high includes critical, gateway connected toast fires once per session via sessionStorage guard',
    files: [
      'frontend/contexts/RiskFlowContext.tsx',
      'frontend/components/RiskFlowPanel.tsx',
      'frontend/contexts/GatewayContext.tsx',
    ],
  },
  {
    date: '2026-03-10T21:00:00',
    agent: 'claude-code',
    summary: 'Track 3 NarrativeFlow + app-wide persistence: added critical severity throughout. severity-config.ts gets critical (orange). RiskFlowImportModal SEVERITY_LABELS gets critical. RiskFlowPanel isHigh check covers critical. MiniWidget severity dot covers critical (orange). NewsSection severityLabel/impliedPoints/color all handle critical (24 base pts, orange). All backend-sourced items now score/render correctly.',
    files: [
      'frontend/lib/severity-config.ts',
      'frontend/components/narrative/RiskFlowImportModal.tsx',
      'frontend/components/RiskFlowPanel.tsx',
      'frontend/components/mission-control/RiskFlowMiniWidget.tsx',
      'frontend/components/feed/NewsSection.tsx',
    ],
  },
  {
    date: '2026-03-10T20:00:00',
    agent: 'claude-code',
    summary: 'Track 2 frontend core fix: wire /api/riskflow/feed into RiskFlowContext. Added pollBackendFeed() (30s interval, minMacroLevel=2, limit=30), backendAlerts state, mapBackendSource() and macroLevelToSeverity() helpers. Merge order: notionAlerts → backendAlerts (deduped) → rssAlerts. Extended AlertSeverity with critical, AlertSource union with all backend source types, RiskFlowAlert.symbols/isBreaking fields.',
    files: [
      'frontend/contexts/RiskFlowContext.tsx',
      'frontend/lib/riskflow-feed.ts',
    ],
  },
  {
    date: '2026-03-10T19:00:00',
    agent: 'claude-code',
    summary: 'Track 1 level filter + warm cache: handlePreload minMacroLevel 3→2; feed-service default minMacroLevel 3→2; econ-triggered-poller warm cache filter high→medium, slice 10→30 (Medium+ seed).',
    files: [
      'backend-hono/src/routes/riskflow/handlers.ts',
      'backend-hono/src/services/riskflow/feed-service.ts',
      'backend-hono/src/services/twitter-cli/econ-triggered-poller.ts',
    ],
  },
  {
    date: '2026-03-10T18:00:00',
    agent: 'claude-code',
    summary: 'RiskFlow + MDB: POST /api/notion/mdb-report/generate (AI brief → Notion, single-entry enforcement), useSourceStatus hook polling /api/riskflow/sources, RiskFlowPanel redesign (Priority+Source dropdowns, X/FJ filter, Notion+X status dots, placeholder "Polling Sources…"), NewsSection same filter redesign + status dots, FooterToolbar Notion+X status indicators. Also: NotionService.generateMdbReport(), writeMDBReportToNotion(), bustBriefCache(), handleGetSources backend handler.',
    files: [
      'backend-hono/src/routes/notion/index.ts',
      'backend-hono/src/routes/riskflow/handlers.ts',
      'backend-hono/src/routes/riskflow/index.ts',
      'backend-hono/src/services/notion-service.ts',
      'frontend/hooks/useSourceStatus.ts',
      'frontend/components/RiskFlowPanel.tsx',
      'frontend/components/feed/NewsSection.tsx',
      'frontend/components/layout/FooterToolbar.tsx',
      'frontend/lib/services.ts',
    ],
  },
  {
    date: '2026-03-10T12:00:00',
    agent: 'claude-code',
    summary: 'MCP T1 Foundation: registry, types, config, backend API, frontend service. Defines 8 MCP servers (playwright, fmp, exa, notion, unusual-whales, yahoo-finance, twitter-cli, alpha-vantage). Backend: types/mcp.ts, services/mcp/registry.ts (async install/env checks via execFileNoThrow), routes/mcp/ (GET /, PATCH /:id/toggle, GET /:id/health). Frontend: types/mcp.ts, lib/mcp-service.ts, McpService added to BackendClient. .env: EXA_API_KEY, ALPHA_VANTAGE_API_KEY, X_API_BEARER_TOKEN added.',
    files: [
      'backend-hono/src/types/mcp.ts',
      'backend-hono/src/services/mcp/registry.ts',
      'backend-hono/src/routes/mcp/index.ts',
      'backend-hono/src/routes/mcp/handlers.ts',
      'backend-hono/src/routes/index.ts',
      'backend-hono/.env',
      'frontend/types/mcp.ts',
      'frontend/lib/mcp-service.ts',
      'frontend/lib/services.ts',
      'src/lib/changelog.ts',
    ],
  },
  {
    date: '2026-03-10T10:30:00',
    agent: 'claude-code',
    summary: 'MCP T3 — Connector Popup UI: McpConnectorPopup slide-up panel next to attach button, Plug2 icon with active-count badge, grouped by category (Data/Search/Social/Browser/Productivity), per-server toggle with status dots, API-key warnings. useMcpConnectors hook (localStorage persistence + best-effort backend sync). mcpServers injected into every chat request. Static fallback defaults when T1 backend routes not yet available.',
    files: [
      'frontend/types/mcp.ts',
      'frontend/components/chat/McpConnectorPopup.tsx',
      'frontend/hooks/useMcpConnectors.ts',
      'frontend/components/chat/PulseChatInput.tsx',
      'frontend/components/chat/ChatInputArea.tsx',
      'frontend/components/chat/hooks/useOpenClawChat.ts',
    ],
  },
  {
    date: '2026-03-10T14:00:00',
    agent: 'claude-code',
    summary: 'T5 Market Data Layer: FMP quotes/VIX + Unusual Whales GEX/walls/flow. New service layer at services/market-data/ (types, fmp-market, unusual-whales, index). Routes at /api/market-data/quote/:symbol, /vix, /gex/:symbol, /walls/:symbol, /flow/:symbol, /context/:symbol. MarketDataService added to frontend BackendClient. UW endpoints return 503 gracefully when API key absent. FMP_API_KEY + UNUSUAL_WHALES_API_KEY wired into .env.',
    files: [
      'backend-hono/src/services/market-data/types.ts',
      'backend-hono/src/services/market-data/fmp-market.ts',
      'backend-hono/src/services/market-data/unusual-whales.ts',
      'backend-hono/src/services/market-data/index.ts',
      'backend-hono/src/routes/market-data/index.ts',
      'backend-hono/src/routes/market-data/handlers.ts',
      'backend-hono/src/routes/index.ts',
      'backend-hono/.env',
      'frontend/types/market-data.ts',
      'frontend/lib/services.ts',
    ],
  },
  {
    date: '2026-03-10T12:00:00',
    agent: 'claude-code',
    summary: 'T2: twitter-cli poller — cookie-based Twitter scraping (no rate limits) linked to Econ Calendar Notion DB. Financial Juice emoji-tier filter (medium+ only into RiskFlow). execFileNoThrow safe subprocess util. TwitterCli NewsSource added. 60s event-triggered polling around active econ events.',
    files: [
      'backend-hono/src/utils/execFileNoThrow.ts',
      'backend-hono/src/services/twitter-cli/twitter-cli-service.ts',
      'backend-hono/src/services/twitter-cli/fj-emoji-filter.ts',
      'backend-hono/src/services/twitter-cli/econ-triggered-poller.ts',
      'backend-hono/src/services/twitter-cli/index.ts',
      'backend-hono/src/types/riskflow.ts',
      'backend-hono/src/services/headline-parser.ts',
      'backend-hono/src/services/riskflow/feed-service.ts',
      'backend-hono/src/index.ts',
    ],
  },
  {
    date: '2026-03-10T14:00:00',
    agent: 'claude-code',
    summary: 'T4 QuickPulse backend: screenshot-service.ts (Playwright inline-script screenshot, isPlaywrightReady check), quick-pulse.ts handler (POST /api/ai/quick-pulse — auto-screenshot fallback via Playwright, multimodal content → OpenClaw pma-1, JSON parse with fence-strip, auto-screenshot in response). Types: backend/src/types/quick-pulse.ts + frontend/types/quick-pulse.ts. Route registered in ai/index.ts. playwright added to backend package.json.',
    files: [
      'backend-hono/src/services/screenshot-service.ts',
      'backend-hono/src/routes/ai/handlers/quick-pulse.ts',
      'backend-hono/src/types/quick-pulse.ts',
      'frontend/types/quick-pulse.ts',
      'backend-hono/src/routes/ai/index.ts',
      'backend-hono/package.json',
    ],
  },
  {
    date: '2026-03-10T12:00:00',
    agent: 'claude-code',
    summary: 'Cursor-style message queue + agent cognition visualization. Backend: chat-queue.ts (in-memory, max 2 slots per conversation), cognition-emitter.ts (EventEmitter for pipeline steps), queue.ts handler (enqueue/status/cancel + cognition SSE stream at GET /api/ai/cognition/stream). chat.ts instrumented with cognition events (agent-route, context-build, tool-dispatch, gateway-call, response-ready, error). Frontend: useChatQueue.ts hook, CognitionPanel.tsx with live SSE step rendering + auto-collapse, lastRequestId threaded through useOpenClawRuntime → ChatInterface → PulseThread.',
    files: [
      'backend-hono/src/services/chat-queue.ts',
      'backend-hono/src/services/cognition-emitter.ts',
      'backend-hono/src/routes/ai/handlers/queue.ts',
      'backend-hono/src/routes/ai/handlers/chat.ts',
      'backend-hono/src/routes/ai/index.ts',
      'frontend/hooks/useChatQueue.ts',
      'frontend/components/chat/CognitionPanel.tsx',
      'frontend/components/chat/hooks/useOpenClawChat.ts',
      'frontend/components/chat/hooks/useChatSession.ts',
      'frontend/components/chat/useOpenClawRuntime.ts',
      'frontend/components/chat/PulseThread.tsx',
      'frontend/components/ChatInterface.tsx',
      'frontend/styles/custom.css',
    ],
  },
  {
    date: '2026-03-09T23:00:00',
    agent: 'claude-code',
    summary: 'Conversation history persistence: useOpenClawChat hydrates messages from GET /api/ai/conversations/:id on remount. Fixes chat reverting to init screen on tab switch or panel close. hydratedRef guards against double-fetch. Surface isolation (analysis vs askharp) preserved.',
    files: ['frontend/components/chat/hooks/useOpenClawChat.ts'],
  },
  {
    date: '2026-03-09T22:00:00',
    agent: 'claude-code',
    summary: 'Switched Groq models from llama-3.3-70b-versatile (100K TPD, worst limit) to task-optimized models: Scout (30K TPM, 500K TPD) for fast/realtime, Maverick 128E (MoE, 500K TPD) for research, Kimi K2 (10K TPM) for CAO reasoning. 5x daily token headroom.',
    files: [
      '~/.openclaw/openclaw.json',
      'backend-hono/src/config/ai-config.ts',
      'backend-hono/src/services/openclaw-service.ts',
    ],
  },
  {
    date: '2026-03-10T08:30:00',
    agent: 'claude-code',
    summary: 'Groq as OpenClaw primary model: registered Groq provider in openclaw.json, set Harper primary to groq/llama-3.3-70b-versatile (free tier, ~750 tok/s). ALL agent traffic now routes Pulse → OpenClaw gateway → Groq. Removed direct Groq bypass — everything flows through gateway with ACP provenance. OpenRouter kept as fallback only. Zero API cost.',
    files: [
      '~/.openclaw/openclaw.json',
      'backend-hono/src/config/ai-config.ts',
      'backend-hono/src/services/ai/model-selector.ts',
      'backend-hono/src/services/openclaw-service.ts',
      'backend-hono/src/types/ai-types.ts',
    ],
  },
  {
    date: '2026-03-10T07:00:00',
    agent: 'claude-code',
    summary: 'ACP provenance headers (OpenClaw 3.8): gateway calls now carry X-ACP-Provenance, X-ACP-Origin-Channel, X-ACP-Origin-Session, X-ACP-Origin-Agent, and X-ACP-Trace-Id headers. Pulse channel types defined (analysis, boardroom, intervention, voice). Default mode: meta+receipt. Prevents agents from blindly trusting unidentified inputs.',
    files: [
      'backend-hono/src/services/openclaw-service.ts',
      'backend-hono/src/services/openclaw-handler.ts',
      'backend-hono/.env',
    ],
  },
  {
    date: '2026-03-10T06:00:00',
    agent: 'claude-code',
    summary: 'Relabeled ER Scoring → Trading Journal across nav, breadcrumbs, and panel header. Feature is PsychAssist emotional regulation history (not fundamental earnings analysis). NavSidebar label + description updated, TopHeader/SectionBreadcrumb TAB_LABELS updated, EarningsHistoryPanel header renamed.',
    files: [
      'frontend/components/layout/NavSidebar.tsx',
      'frontend/components/layout/TopHeader.tsx',
      'frontend/components/layout/SectionBreadcrumb.tsx',
      'frontend/components/earnings/EarningsHistoryPanel.tsx',
    ],
  },
  {
    date: '2026-03-10T05:00:00',
    agent: 'claude-code',
    summary: 'Post-review bug fixes: (1) AskHarpChatPanel thinkHarder toggle was broken — state lived inside inner component but runtime was created in outer scope with hardcoded false. Lifted thinkHarder state to outer AskHarpChatPanel so it actually reaches useOpenClawRuntime. (2) NavTab type mismatch — earnings tab added to SectionBreadcrumb and TopHeader to match NavSidebar.',
    files: [
      'frontend/components/chat/AskHarpChatPanel.tsx',
      'frontend/components/layout/SectionBreadcrumb.tsx',
      'frontend/components/layout/TopHeader.tsx',
    ],
  },
  {
    date: '2026-03-10T04:00:00',
    agent: 'claude-code',
    summary: 'ER Scoring History — Notion-backed psych journal for earnings reviews. ERStoreAdapter interface with Notion adapter (auto-creates DB via setup endpoint). Backend CRUD + filter/pagination at /api/er-scoring, agent retrieval with token budget. Frontend: ERScoringProvider context, EarningsHistoryPanel with filter bar + new entry form, EarningsReviewSlideout for detail/edit. Nav sidebar tab "ER Scoring". Psych agent intent pattern routes to Harper for behavioral analysis.',
    files: [
      'backend-hono/src/types/earnings-history.ts',
      'backend-hono/src/services/earnings-history/adapter.ts',
      'backend-hono/src/services/earnings-history/notion-adapter.ts',
      'backend-hono/src/services/earnings-history/index.ts',
      'backend-hono/src/routes/earnings/index.ts',
      'backend-hono/src/routes/earnings/handlers.ts',
      'backend-hono/src/routes/index.ts',
      'backend-hono/src/services/openclaw-handler.ts',
      'frontend/types/earnings-history.ts',
      'frontend/contexts/EarningsHistoryContext.tsx',
      'frontend/components/earnings/EarningsHistoryPanel.tsx',
      'frontend/components/earnings/EarningsReviewSlideout.tsx',
      'frontend/lib/services.ts',
      'frontend/lib/layoutOrderStorage.ts',
      'frontend/components/layout/NavSidebar.tsx',
      'frontend/components/layout/MainLayout.tsx',
    ],
  },
  {
    date: '2026-03-09T22:00:00',
    agent: 'claude-code',
    summary: 'Chat reliability hardening (Plan 1.3): (1) No blank assistant bubble — PulseAssistantMessage gates on content presence, only renders once text-delta or reasoning arrives. PulseThinkingIndicator handles visual feedback separately. (2) Per-surface session isolation — each chat surface (Analysis, AskHarp, Floating, Research) gets its own conversationId via surfaceId param, preventing context bleed across surfaces. (3) Error visibility in thread — lastError now renders as an AlertCircle banner inside PulseThread (not just the input area), so errors are visible even when scrolled up. (4) Boardroom audit — confirmed read-only (Notion embed + intervention sidebar, no mutating tools).',
    files: [
      'frontend/components/chat/PulseThread.tsx',
      'frontend/components/chat/useOpenClawRuntime.ts',
      'frontend/components/chat/hooks/useChatSession.ts',
      'frontend/components/chat/AskHarpChatPanel.tsx',
      'frontend/components/chat/PulseFloatingChat.tsx',
      'frontend/components/ChatInterface.tsx',
      'frontend/components/executive/ResearchDepartment.tsx',
      'frontend/hooks/usePersistentOpenClawConversation.ts',
      'frontend/lib/openclawAgentRouting.ts',
    ],
  },
  {
    date: '2026-03-10T02:00:00',
    agent: 'claude-code',
    summary: 'Chat UX + Upload + Slash + Permissions: (1) Fixed image attachment pipeline — images now flow through ChatInputArea→PulseComposer→useOpenClawChat→backend as multimodal content parts. (2) Replaced floating attach modal with slide-up panel anchored to composer, added drag-drop and client-side compression. (3) Slash-command launcher — typing / in textarea triggers filtered skill picker with keyboard nav (<=150ms). (4) Brain icon deep-research flow — Exa API integration with graceful fallback, thinkHarder flag wired end-to-end. (5) Permissions — feature flags config, GET /api/ai/features endpoint, server-side skill enforcement, disabled skills show reason in UI. (6) Tool-selection policy — Exa preferred before browser automation.',
    files: [
      'frontend/components/chat/ChatInputArea.tsx',
      'frontend/components/chat/PulseComposer.tsx',
      'frontend/components/chat/PulseChatInput.tsx',
      'frontend/components/chat/PulseAttachPopup.tsx',
      'frontend/components/chat/PulseSkillsPopup.tsx',
      'frontend/components/chat/PulseSlashPicker.tsx',
      'frontend/components/chat/hooks/useOpenClawChat.ts',
      'frontend/components/chat/useOpenClawRuntime.ts',
      'frontend/components/ChatInterface.tsx',
      'frontend/lib/skills.ts',
      'frontend/hooks/useFeatureFlags.ts',
      'backend-hono/src/routes/ai/handlers/chat.ts',
      'backend-hono/src/routes/ai/index.ts',
      'backend-hono/src/services/openclaw-handler.ts',
      'backend-hono/src/services/exa-service.ts',
      'backend-hono/src/services/tool-policy.ts',
      'backend-hono/src/config/feature-flags.ts',
    ],
  },
  {
    date: '2026-03-09T23:30:00',
    agent: 'claude-code',
    summary: 'Critical reliability build: (1) VIX feed hardening — fallback chain Yahoo→backend→cached→degraded, staleness tracking with 2min threshold, status getter, degraded-state UI indicator in IVScoreCard. (2) Config-driven IV scoring — extracted all hardcoded thresholds to iv-scoring-config.json, calculateIVScoreV2 accepts config param, added POST /api/market/iv-scoring/replay endpoint for config testing. Frontend computeIVScore also accepts config override. (3) Voice assistant lifecycle — added error state with 5s auto-recovery, cancel/interrupt support via AbortController, mic permission denied recovery path. (4) Mic arbitration — useMicPermission hook for explicit browser permission tracking, useMicArbitration hook with priority-based lock (VoiceAssistant=10, PsychAssist=5). HeaderVoiceControl wired for cancel-on-click during thinking/speaking and denied-state tooltip.',
    files: [
      'lib/vix-feed.ts',
      'contexts/VIXContext.tsx',
      'components/IVScoreCard.tsx',
      'components/layout/TopHeader.tsx',
      'backend-hono/src/services/iv-scoring-v2.ts',
      'backend-hono/src/config/iv-scoring-config.json',
      'backend-hono/src/routes/market/handlers.ts',
      'backend-hono/src/routes/market/index.ts',
      'frontend/lib/iv-scoring.ts',
      'frontend/hooks/useVoiceAssistant.ts',
      'frontend/types/voice.ts',
      'frontend/components/voice/HeaderVoiceControl.tsx',
    ],
  },
  {
    date: '2026-03-09T22:00:00',
    agent: 'claude-code',
    summary: 'Chat reliability hardening: throw on error responses instead of passing to SSE parser (was causing silent failures), add 65s frontend timeout, wire lastError through useOpenClawRuntime to ChatInterface and AskHarpChatPanel (was hardcoded null), add console warnings for silent catches, defensive try/catch in PulseComposer. Created endpoint parity matrix (7 mismatches documented) and trading blackout policy.',
    files: [
      'frontend/components/chat/hooks/useOpenClawChat.ts',
      'frontend/components/chat/useOpenClawRuntime.ts',
      'frontend/components/ChatInterface.tsx',
      'frontend/components/chat/AskHarpChatPanel.tsx',
      'frontend/components/chat/PulseComposer.tsx',
      'docs/ENDPOINT-PARITY-MATRIX.md',
      'docs/BLACKOUT-POLICY.md',
    ],
  },
  {
    date: '2026-03-09T15:15:00.000Z',
    agent: 'openclaw',
    summary:
      'Stabilized chat steer queue to prevent thread blanking/timeouts: replaced assistant-ui internal queued append during active runs with a local single-item steer queue that flushes only after the current run completes.',
    files: [
      'frontend/components/chat/PulseComposer.tsx',
    ],
  },
  {
    date: '2026-03-07T04:00:00',
    agent: 'claude-code',
    summary: 'Fix chat: local OpenClaw is now primary path (was broken by GitHub OAuth token routing all requests to non-existent DeepSeek R1). Enable chatCompletions endpoint on OpenClaw gateway. Replace Kalshi contract codes with Notion Trade Idea titles in all UI surfaces. Rename GitHub Models model from DeepSeek R1 to GPT-4o.',
    files: [
      'backend-hono/src/routes/ai/handlers/chat.ts',
      'backend-hono/src/config/ai-config.ts',
      'backend-hono/src/services/notion-service.ts',
      'backend-hono/src/services/notion-poller.ts',
      'frontend/components/TradeIdeaModal.tsx',
      'frontend/contexts/RiskFlowContext.tsx',
      'frontend/lib/riskflow-feed.ts',
    ],
  },
  {
    date: '2026-03-07T03:30:00',
    agent: 'claude-code',
    summary: 'Footer toolbar slide-up panel with Terminal and Changelog tabs. Terminal has CLI input/output history. Changelog pulls live from changelog.ts. Panel animates open/closed with tab switching.',
    files: [
      'frontend/components/layout/FooterToolbar.tsx',
    ],
  },
  {
    date: '2026-03-07T03:00:00',
    agent: 'claude-code',
    summary: 'Session date logic: after 9PM, dashboard calendar discards past releases and shows upcoming. EconCalendar snaps to next day after 9PM. SessionCalendarList filters past dates and shows "Next Session" label.',
    files: [
      'frontend/components/executive/SessionCalendarList.tsx',
      'frontend/contexts/EconCalendarContext.tsx',
    ],
  },
  {
    date: '2026-03-07T02:30:00',
    agent: 'claude-code',
    summary: 'Fix Trade Ideas "undefined" ticker — empty Ticker rich_text now falls back to Trade Idea title. Frontend RiskFlowContext uses displayName fallback for headline/summary/tradeIdea fields.',
    files: [
      'backend-hono/src/services/notion-service.ts',
      'frontend/contexts/RiskFlowContext.tsx',
    ],
  },
  {
    date: '2026-03-07T01:00:00',
    agent: 'claude-code',
    summary: 'Switched GitHub Models from Kimi K2 to DeepSeek R1. OAuth popup window flow (fixes white screen). Removed Kimi branding from CTA. GitHub-authenticated users now route to DeepSeek R1 instead of local OpenClaw. Clean error messages on model failure instead of silent fallback.',
    files: [
      'backend-hono/src/config/ai-config.ts',
      'backend-hono/src/routes/ai/handlers/chat.ts',
      'backend-hono/src/routes/auth/github.ts',
      'frontend/components/chat/ChatHeader.tsx',
      'frontend/components/chat/hooks/useOpenClawChat.ts',
      'frontend/components/GitHubOAuthCallback.tsx',
      'frontend/contexts/AuthContext.tsx',
    ],
  },
  {
    date: '2026-03-06T23:30:00',
    agent: 'claude-code',
    summary: 'Renamed NTN → MDB (Morning Daily Brief) throughout codebase. Settings save fix (skip backend call when unauthenticated). RiskFlow panel smooth collapse/expand transition. Regime Tracker modal rounded edges. Chat error message improved for backend-unavailable state. iFrames settings section added to SettingsPanel.',
    files: [
      'backend-hono/src/services/notion-service.ts',
      'backend-hono/src/services/openclaw-handler.ts',
      'backend-hono/src/services/openclaw-service.ts',
      'backend-hono/src/routes/notion/index.ts',
      'backend-hono/src/routes/narrative/handlers.ts',
      'frontend/lib/services.ts',
      'frontend/types/api.ts',
      'frontend/components/MDBReportModal.tsx',
      'frontend/components/ChatInterface.tsx',
      'frontend/components/SystemFeed.tsx',
      'frontend/components/chat/ChatHeader.tsx',
      'frontend/components/chat/ChatGreeting.tsx',
      'frontend/components/chat/constants.ts',
      'frontend/components/feed/FeedSection.tsx',
      'frontend/components/search/SearchModal.tsx',
      'frontend/components/executive/ExecutiveDashboard.tsx',
      'frontend/components/narrative/CatalystCard.tsx',
      'frontend/components/narrative/RiskFlowImportModal.tsx',
      'frontend/components/RiskFlowPanel.tsx',
      'frontend/components/regimes/RegimeTrackerModal.tsx',
      'frontend/components/chat/hooks/useOpenClawChat.ts',
      'frontend/components/SettingsPanel.tsx',
      'frontend/contexts/SettingsContext.tsx',
    ],
  },
  {
    date: '2026-03-06T22:00:00',
    agent: 'claude-code',
    summary: 'Catalyst Import T1: Backend LLM scoring endpoints for NarrativeFlow. POST /api/narrative/score-riskflow and /score-brief — accepts RiskFlow items or daily brief text, scores via LLM (sentiment task model), returns ScoredCandidate array with keyword fallback on LLM failure.',
    files: [
      'backend-hono/src/routes/narrative/handlers.ts',
      'backend-hono/src/routes/narrative/index.ts',
      'backend-hono/src/routes/index.ts',
    ],
  },
  {
    date: '2026-03-06T20:00:00',
    agent: 'claude-code',
    summary: 'Sprint 4: Regime Tracker — institutional/session/report trading windows with W-L tracking. Mission Control mini-screener, dashboard preview card, full popup modal, backend API endpoint, localStorage persistence, skill prefix integration.',
    files: [
      'frontend/lib/regimes.ts',
      'frontend/lib/regime-time.ts',
      'frontend/lib/regime-store.ts',
      'frontend/components/mission-control/RegimeMini.tsx',
      'frontend/components/dashboard/RegimeCard.tsx',
      'frontend/components/regimes/RegimeTrackerModal.tsx',
      'backend-hono/src/routes/regimes/index.ts',
      'backend-hono/src/routes/index.ts',
      'frontend/components/mission-control/MissionControlPanel.tsx',
      'frontend/components/layout/MainLayout.tsx',
      'frontend/components/executive/ExecutiveDashboard.tsx',
      'frontend/lib/layoutOrderStorage.ts',
      'frontend/lib/skillPrefixes.ts',
    ],
  },
  {
    date: '2026-03-06T18:00:00',
    agent: 'claude-code',
    summary: 'Sprint 2: Theme System — 6 presets (solvys-gold, ios, project-x, dark-trading, miami-heat, monocolor), CSS variable architecture, ThemeProvider context, ThemeSettings panel with live preview + custom HEX inputs, localStorage persistence. Migrated key components to CSS variables.',
    files: [
      'frontend/lib/theme.ts',
      'frontend/contexts/ThemeContext.tsx',
      'frontend/components/settings/ThemeSettings.tsx',
      'frontend/index.css',
      'frontend/App.tsx',
      'frontend/components/chat/ChatHeader.tsx',
      'frontend/components/chat/ChatGreeting.tsx',
      'frontend/components/chat/ChatMessageBubble.tsx',
      'frontend/components/chat/PulseThinkingIndicator.tsx',
      'frontend/components/chat/PulseSkillsPopup.tsx',
      'frontend/components/layout/NavSidebar.tsx',
      'frontend/components/SettingsPanel.tsx',
    ],
  },
  {
    date: '2026-03-05T20:30:00',
    agent: 'claude-code',
    summary: 'RiskFlow layout fix: removed RiskFlow from Mission Control panel, gave Mission Control full right panel height. Added Proposals filter tab to RiskFlow section (NewsSection) alongside All/High/Medium filters. Updated DMG.',
    files: [
      'frontend/components/layout/MainLayout.tsx',
      'frontend/components/feed/NewsSection.tsx',
      'frontend/lib/layoutOrderStorage.ts',
    ],
  },
  {
    date: '2026-03-05T18:14:00.000Z',
    agent: 'openclaw',
    summary:
      '21st-style chat polish pass implemented directly in Pulse (while preserving black/gold palette): upgraded Analysis + Ask Harp message cards and composer shell, refined action controls, and improved visual hierarchy/spacing for modern chat UX without changing OpenClaw transport behavior.',
    files: [
      'frontend/components/chat/PulseChatInput.tsx',
      'frontend/components/ChatInterface.tsx',
      'frontend/components/chat/AskHarpChatPanel.tsx',
    ],
  },
  {
    date: '2026-03-05T18:03:00.000Z',
    agent: 'openclaw',
    summary:
      'Chat UI thinking pass (Analysis + Ask Harp): added radar pulse indicator, expanded finance thinking phrase set, and kept thinking pane visible when reasoning is present so users can inspect model thought stream after response completes.',
    files: [
      'frontend/components/chat/PulseThinkingIndicator.tsx',
      'frontend/components/ChatInterface.tsx',
      'frontend/components/chat/AskHarpChatPanel.tsx',
    ],
  },
  {
    date: '2026-03-05T16:58:00.000Z',
    agent: 'openclaw',
    summary:
      'Chat interface reliability patch: surfaced transport/backend errors directly in Analysis + Ask Harp chat panels, cleared stale errors on resend, and tightened gateway health checks to avoid false "Gateway connected" states when non-health HTML is returned. This makes chat failures visible instead of silently hanging and fixes misleading gateway status toasts.',
    files: [
      'frontend/components/chat/hooks/useOpenClawChat.ts',
      'frontend/components/ChatInterface.tsx',
      'frontend/components/chat/AskHarpChatPanel.tsx',
      'frontend/contexts/GatewayContext.tsx',
    ],
  },
  {
    date: '2026-03-04T22:55:00.000Z',
    agent: 'openclaw',
    summary:
      'Fixed protected API auth middleware matching so nested routes are actually authenticated (added wildcard middleware for /api/* groups, including /api/ai/* and /api/riskflow/*). This resolves Pulse agent chat unauthorized failures where c.get("userId") was undefined in /api/ai/chat.',
    files: ['backend-hono/src/routes/index.ts'],
  },
  {
    date: '2026-03-04T17:02:00.000Z',
    agent: 'claude-code',
    summary:
      'FortyFortyClub uploaded to QuantConnect (project 28682111), compiled successfully, baseline backtest launched. Fixed QC enum names: INTERACTIVE_BROKERS_BROKERAGE→QUANT_CONNECT_BROKERAGE (live uses Rithmic/Lucid), MICRO_NASDAQ100_E_MINI→MICRO_NASDAQ_100_E_MINI, SP500_E_MINI→SP_500_E_MINI. Confirmation instrument is /ES (full-size), not /MES.',
    files: ['quantconnect/FortyFortyClub/main.py'],
  },
  {
    date: '2026-03-04T12:00:00.000Z',
    agent: 'claude-code',
    summary:
      'Phase I: FortyFortyClub QC algorithm — full implementation. Liquidity sweep reversal on /MNQ with Antilag (tick velocity + NQ/ES alignment) confirmation. Includes: fib sweep detection (20-candle swing H/L), 4-phase trailing stop, scale-in logic (+5 micros at ATR≥55% from 100 EMA), PDPT lockout ($1,550 combine mode), news blackout (120s), and daily reset. Ready for upload to QuantConnect via qc-mcp once Docker/MCP connected.',
    files: ['quantconnect/FortyFortyClub/main.py'],
  },
  {
    date: '2026-03-03T23:00:00.000Z',
    agent: 'claude-code',
    summary:
      'Layout polish pass on new Notion trade idea components. TradeIdeaModal: tighter padding (px-4/py-3 header, px-4/py-3.5 body, px-4/py-2.5 footer), StatBox reduced to px-2.5 py-2 with text-xs value, price values formatted with formatPrice() helper ($0.XX for Kalshi contracts, $X,XXX.XX for equities).',
    files: ['frontend/components/TradeIdeaModal.tsx'],
  },
  {
    date: '2026-03-03T22:30:00.000Z',
    agent: 'claude-code',
    summary:
      'Notion Polling → RiskFlow + KPI Live Data + Trade Idea Modals. Backend: notion-service.ts extended with queryTradeIdeas/queryDailyPnL using verified live DB schema (Trade Ideas: Ticker/Direction/EntryPrice/Confidence/Analyst; Daily P&L: Net P&L/Win Rate/Trades Taken). notion-poller.ts polls 60s, generates OpenClaw descriptions for new ideas. Routes: /api/notion/trade-ideas, /performance, /poll-status registered as public. NOTION_API_KEY added to .env (correct key from memory). Frontend: RiskFlowAlert extended with source notion-trade-idea + TradeIdeaDetail type. RiskFlowContext polls Notion 60s, merges trade ideas at top of feed. NotionService added to services.ts + BackendClient. TradeIdeaModal.tsx: dark overlay, gold-bordered card, price levels + R/R stats + OpenClaw brief. RiskFlowPanel: TradeIdeaRow with gold left-border + click-to-modal, Ideas filter tab. ExecutiveDashboard Phase 3D: live KPIs from /api/notion/performance merge on top of mock.',
    files: [
      'backend-hono/src/services/notion-service.ts',
      'backend-hono/src/services/notion-poller.ts',
      'backend-hono/src/routes/notion/handlers.ts',
      'backend-hono/src/routes/notion/index.ts',
      'backend-hono/src/routes/index.ts',
      'backend-hono/src/index.ts',
      'backend-hono/.env',
      'frontend/lib/riskflow-feed.ts',
      'frontend/contexts/RiskFlowContext.tsx',
      'frontend/lib/services.ts',
      'frontend/components/TradeIdeaModal.tsx',
      'frontend/components/RiskFlowPanel.tsx',
      'frontend/components/executive/ExecutiveDashboard.tsx',
    ],
  },
  {
    date: '2026-03-03T21:00:00.000Z',
    agent: 'claude-code',
    summary:
      'Phase 3A-C: Notion backend service (NTN brief from Harper Messages DB, schedule mock). Frontend NotionService.getNtnBrief/getSchedule added. ExecutiveDashboard fetches live NTN brief, schedule, and Intraday PnL KPI from account. Phase 4B: FooterToolbar component (changelog viewer, CLI input, system status). Wired into MainLayout.',
    files: [
      'backend-hono/src/services/notion-service.ts',
      'backend-hono/src/routes/notion/index.ts',
      'backend-hono/src/routes/index.ts',
      'frontend/lib/services.ts',
      'frontend/components/executive/ExecutiveDashboard.tsx',
      'frontend/components/layout/FooterToolbar.tsx',
      'frontend/components/layout/MainLayout.tsx',
    ],
  },
  {
    date: '2026-03-03T20:00:00.000Z',
    agent: 'claude-code',
    summary:
      'Phase 1C: Removed History panel (ConversationSession types, all history state/handlers, History button + left docked panel). Phase 1D: Replaced persona selector with PulseSkillsPopup (showSkills state, onOpenSkills prop). Phase 2A: Removed stray border-l from MissionControlPanel. Phase 2C: Restructured right stack to 50/50 independent scroll (Mission Control top, RiskFlow bottom), w-96→w-80. Phase 2E: BlindspotsWidget per-item dismiss + clearAll. Phase 4A: TopHeader height -20% (70→56px, 65→52px). Phase 4C-D: IV score wired to quickIVScore(vix) — removed fake random walk.',
    files: [
      'frontend/components/ChatInterface.tsx',
      'frontend/components/mission-control/MissionControlPanel.tsx',
      'frontend/components/layout/MainLayout.tsx',
      'frontend/components/mission-control/BlindspotsWidget.tsx',
      'frontend/components/layout/TopHeader.tsx',
    ],
  },
  {
    date: '2026-03-03T19:00:00.000Z',
    agent: 'claude-code',
    summary:
      'Phase 2 Smart Layout: converted overlay sidebars to docked side panels. History docks left, Checkpoints docks right. Panel open/closed state persists to localStorage via usePanelState hook. Panels animate open/close with CSS width transition (240ms). Fixed onKeyPress → onKeyDown deprecation.',
    files: [
      'frontend/components/ChatInterface.tsx',
    ],
  },
  {
    date: '2026-03-03T18:00:00.000Z',
    agent: 'claude-code',
    summary:
      'Phase 1B checkpoints: enhanced sidebar with date-grouped bookmarks (Today/Yesterday/date), click-away backdrop, compact card layout, Bookmark icon header, footer count. Added groupCheckpointsByDate helper.',
    files: [
      'frontend/components/ChatInterface.tsx',
    ],
  },
  {
    date: '2026-03-03T00:30:00.000Z',
    agent: 'claude-code',
    summary: 'Rithmic Gateway: Python sidecar (FastAPI + async_rithmic) at rithmic-gateway/gateway.py, HTTP API on localhost:3002. Updated rithmic-service.ts to proxy calls to gateway. Added RITHMIC-GATEWAY.md OpenClaw handoff with semi-autonomous + fully-autonomous mode architecture.',
    files: [
      'rithmic-gateway/gateway.py',
      'rithmic-gateway/requirements.txt',
      'rithmic-gateway/.env.example',
      'backend-hono/src/services/rithmic-service.ts',
      'docs/quantconnect/RITHMIC-GATEWAY.md',
    ],
  },
  {
    date: '2026-03-03T01:00:00.000Z',
    agent: 'claude-code',
    summary: 'Phase 1 autopilot: added POST /api/trading/test-trade endpoint wired to Rithmic (primary) / ProjectX (fallback via PRIMARY_BROKER env). Added placeOrder() + searchContracts() to projectx/client.ts. Configured QuantConnect MCP server at localhost:3001.',
    files: [
      'backend-hono/src/services/projectx/client.ts',
      'backend-hono/src/services/trading-service.ts',
      'backend-hono/src/routes/trading/handlers.ts',
      'backend-hono/src/routes/trading/index.ts',
      'docs/quantconnect/AUTOPILOT-IMPLEMENTATION-PHASE-1.md',
    ],
  },
  {
    date: '2026-02-26T16:22:30.000Z',
    agent: 'claude-code',
    summary:
      'Converted Boardroom to a Notion-embedded meeting surface with a countdown timer, documented PIC Notion entity IDs, and added a Kimi Claw backend+frontend trigger for SMS/iMessage workflows.',
    files: [
      'frontend/components/BoardroomView.tsx',
      'frontend/lib/services.ts',
      'frontend/README.md',
      'backend-hono/src/routes/index.ts',
      'backend-hono/src/routes/kimi/index.ts',
      'backend-hono/src/routes/kimi/handlers.ts',
      'backend-hono/src/services/kimi-claw-service.ts',
      'backend-hono/tsconfig.json',
      'backend-hono/.env.example',
      'knowledge-base/notion/PIC-NOTION-ENTITY-MAP.md',
    ],
  },
  {
    date: '2026-02-26T16:26:00.000Z',
    agent: 'claude-code',
    summary:
      'Improved embedded OAuth flows by allowing user-activated top navigation in browser iframes and enabling Electron webview popup handling for Notion/Google/Apple sign-in windows.',
    files: ['frontend/components/layout/EmbeddedBrowserFrame.tsx', 'electron/main.cjs'],
  },
  {
    date: '2026-02-26T16:34:00.000Z',
    agent: 'claude-code',
    summary:
      'Removed manual Kimi SMS UI/API wiring, added cron-derived boardroom meeting schedule endpoint, and updated boardroom countdown + Live/Inactive indicator to follow the schedule.',
    files: [
      'frontend/components/BoardroomView.tsx',
      'frontend/lib/services.ts',
      'backend-hono/src/services/boardroom-schedule.ts',
      'backend-hono/src/routes/boardroom/handlers.ts',
      'backend-hono/src/routes/boardroom/index.ts',
      'backend-hono/src/routes/index.ts',
      'backend-hono/.env.example',
      'knowledge-base/notion/PIC-NOTION-ENTITY-MAP.md',
    ],
  },
  {
    date: '2026-02-26T18:45:00.000Z',
    agent: 'claude-code',
    summary:
      'Fixed missing user bubbles in Ask Harp/Intervention, added per-agent persistent OpenClaw threads with agent override support, introduced chat checkpoints for recall, and adjusted Mission Control RiskFlow + Account Tracker KPIs (status + platform tracker).',
    files: [
      'backend-hono/src/services/clawdbot-sessions.ts',
      'backend-hono/src/routes/ai/handlers/chat.ts',
      'backend-hono/src/types/ai-chat.ts',
      'frontend/components/chat/hooks/useOpenClawChat.ts',
      'frontend/components/chat/PulseFloatingChat.tsx',
      'frontend/components/executive/ResearchDepartment.tsx',
      'frontend/components/ChatInterface.tsx',
      'frontend/lib/chatCheckpoints.ts',
      'frontend/hooks/usePersistentOpenClawConversation.ts',
      'frontend/lib/openclawAgentRouting.ts',
      'frontend/components/RiskFlowPanel.tsx',
      'frontend/components/layout/MainLayout.tsx',
      'frontend/components/mission-control/AccountTrackerWidget.tsx',
    ],
  },
  {
    date: '2026-02-26T19:05:00.000Z',
    agent: 'claude-code',
    summary:
      'Added a dockable PsychAssist widget for Zen layout: drag the widget into the heading toolbar to fuse, or click the PiP button to dock/undock.',
    files: [
      'frontend/components/layout/PsychAssistDockable.tsx',
      'frontend/components/layout/MainLayout.tsx',
      'frontend/components/layout/TopHeader.tsx',
      'frontend/components/layout/FloatingWidget.tsx',
    ],
  },
  {
    date: '2026-02-26T19:18:00.000Z',
    agent: 'claude-code',
    summary:
      'Fixed Full Screen / Expand to Analysis on floating chat: exit TopStepX when expanding so the Analysis (sidebar) chat is shown instead of a white screen.',
    files: ['frontend/components/layout/MainLayout.tsx'],
  },
  {
    date: '2026-02-26T19:28:00.000Z',
    agent: 'claude-code',
    summary:
      'Fixed React #300 (fewer hooks): move early return after all hooks in PulseFloatingChat. Gateway health check URL configurable via VITE_GATEWAY_URL.',
    files: ['frontend/components/chat/PulseFloatingChat.tsx', 'frontend/contexts/GatewayContext.tsx'],
  },
  {
    date: '2026-02-28T06:30:00.000Z',
    agent: 'openclaw',
    summary:
      'Zen layout polish pass: widened docked PsychAssist space, removed Zen floating Day P&L card, stripped iframe borders/padding, added power-off controls, tightened Mission Control width + card ordering, improved RiskFlow preview density, moved Account Tracker loading status to header, removed Loss Limit/Daily Target KPIs, and disabled mock RiskFlow fallback in News.',
    files: [
      'frontend/components/layout/PsychAssistDockable.tsx',
      'frontend/components/layout/TopHeader.tsx',
      'frontend/components/layout/MainLayout.tsx',
      'frontend/components/layout/FloatingWidget.tsx',
      'frontend/components/TopStepXBrowser.tsx',
      'frontend/components/mission-control/MissionControlPanel.tsx',
      'frontend/components/mission-control/AccountTrackerWidget.tsx',
      'frontend/components/RiskFlowPanel.tsx',
      'frontend/components/feed/NewsSection.tsx',
    ],
  },
  {
    date: '2026-03-03T04:00:00.000Z',
    agent: 'claude-code',
    summary:
      'Added Rithmic test trade endpoint plan to AGENT-2 task doc: service (executeTestTrade + getPointValue for micros), handler, route spec with strategy-specific targets, PDPT caps, scale-in limits. Types already completed in prior session.',
    files: ['docs/AGENT-2-CLAUDE-CODE-TASKS.md'],
  },
];

