// Code generated by the Encore 1.51.6 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly account: account.ServiceClient
    public readonly ai: ai.ServiceClient
    public readonly er: er.ServiceClient
    public readonly events: events.ServiceClient
    public readonly news: news.ServiceClient
    public readonly notifications: notifications.ServiceClient
    public readonly projectx: projectx.ServiceClient
    public readonly trading: trading.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.account = new account.ServiceClient(base)
        this.ai = new ai.ServiceClient(base)
        this.er = new er.ServiceClient(base)
        this.events = new events.ServiceClient(base)
        this.news = new news.ServiceClient(base)
        this.notifications = new notifications.ServiceClient(base)
        this.projectx = new projectx.ServiceClient(base)
        this.trading = new trading.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { auth as auth_auth } from "~backend/auth/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_auth> | AuthDataGenerator
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_account_create_create } from "~backend/account/create";
import { get as api_account_get_get } from "~backend/account/get";
import { updateSettings as api_account_update_settings_updateSettings } from "~backend/account/update_settings";
import { updateTier as api_account_update_tier_updateTier } from "~backend/account/update_tier";

export namespace account {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.updateSettings = this.updateSettings.bind(this)
            this.updateTier = this.updateTier.bind(this)
        }

        /**
         * Creates a new account for the authenticated user.
         */
        public async create(params: RequestType<typeof api_account_create_create>): Promise<ResponseType<typeof api_account_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/account`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_account_create_create>
        }

        /**
         * Retrieves account information for the authenticated user.
         */
        public async get(): Promise<ResponseType<typeof api_account_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/account`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_account_get_get>
        }

        /**
         * Updates trading settings for the authenticated user account.
         */
        public async updateSettings(params: RequestType<typeof api_account_update_settings_updateSettings>): Promise<void> {
            await this.baseClient.callTypedAPI(`/account/settings`, {method: "PATCH", body: JSON.stringify(params)})
        }

        /**
         * Updates the billing tier for the authenticated user account.
         */
        public async updateTier(params: RequestType<typeof api_account_update_tier_updateTier>): Promise<void> {
            await this.baseClient.callTypedAPI(`/account/tier`, {method: "PATCH", body: JSON.stringify(params)})
        }
    }
}


export namespace auth {
}

/**
 * ER (Emotional Resonance) Service Types
 */
export interface SaveERSessionRequest {
    finalScore: number;
    timeInTiltSeconds: number;
    infractionCount: number;
    sessionDurationSeconds: number;
    maxTiltScore?: number;
    maxTiltTime?: Date;
}

export interface SaveERSessionResponse {
    success: boolean;
    sessionId: number;
}

export interface ERSession {
    id: number;
    sessionStart: Date;
    sessionEnd: Date | null;
    finalScore: number;
    timeInTiltSeconds: number;
    infractionCount: number;
    sessionDurationSeconds: number;
    sessionDurationFormatted: string;
    maxTiltScore: number | null;
    maxTiltTime: Date | null;
    createdAt: Date;
}

export interface GetERSessionsResponse {
    sessions: ERSession[];
}

export interface SaveERSnapshotRequest {
    sessionId: number;
    score: number;
    state: "stable" | "neutral" | "tilt";
    audioLevels?: string;
    keywords?: string[];
}

export interface OvertradingStatus {
    isOvertrading: boolean;
    tradesInWindow: number;
    windowMinutes: number;
    threshold: number;
    recentTrades: Array<{
        symbol: string;
        openedAt: Date;
        side: string;
    }>;
    warning?: string;
}

export namespace er {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.saveSession = this.saveSession.bind(this)
            this.getERSessions = this.getERSessions.bind(this)
            this.saveSnapshot = this.saveSnapshot.bind(this)
            this.checkOvertrading = this.checkOvertrading.bind(this)
        }

        /**
         * Save an ER session
         */
        public async saveSession(params: SaveERSessionRequest): Promise<SaveERSessionResponse> {
            const resp = await this.baseClient.callTypedAPI(`/er/save-session`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as SaveERSessionResponse
        }

        /**
         * Get ER sessions for the user
         */
        public async getERSessions(): Promise<GetERSessionsResponse> {
            const resp = await this.baseClient.callTypedAPI(`/er/sessions`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as GetERSessionsResponse
        }

        /**
         * Save an ER snapshot
         */
        public async saveSnapshot(params: SaveERSnapshotRequest): Promise<{ success: boolean }> {
            const resp = await this.baseClient.callTypedAPI(`/er/snapshot`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as { success: boolean }
        }

        /**
         * Check for overtrading
         */
        public async checkOvertrading(params: { windowMinutes?: number; threshold?: number }): Promise<OvertradingStatus> {
            const query = makeRecord<string, string | string[]>({
                windowMinutes: params.windowMinutes?.toString(),
                threshold: params.threshold?.toString(),
            })
            const resp = await this.baseClient.callTypedAPI(`/er/overtrading`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as OvertradingStatus
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_events_create_create } from "~backend/events/create";
import { list as api_events_list_list } from "~backend/events/list";

export namespace events {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.list = this.list.bind(this)
            this.seed = this.seed.bind(this)
        }

        /**
         * Creates a new system event.
         */
        public async create(params: RequestType<typeof api_events_create_create>): Promise<void> {
            await this.baseClient.callTypedAPI(`/events`, {method: "POST", body: JSON.stringify(params)})
        }

        /**
         * Retrieves system events for the authenticated user ordered by creation date.
         */
        public async list(params: RequestType<typeof api_events_list_list>): Promise<ResponseType<typeof api_events_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/events`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_events_list_list>
        }

        /**
         * Creates sample system events for testing purposes.
         */
        public async seed(): Promise<void> {
            await this.baseClient.callTypedAPI(`/events/seed`, {method: "POST", body: undefined})
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { chat as api_ai_chat_chat } from "~backend/ai/chat";
import { checkTape as api_ai_check_tape_checkTape } from "~backend/ai/chat";
import { generateDailyRecap as api_ai_generate_daily_recap_generateDailyRecap } from "~backend/ai/chat";
import { listConversations as api_ai_list_conversations_listConversations } from "~backend/ai/chat";
import { getConversation as api_ai_get_conversation_getConversation } from "~backend/ai/chat";

export namespace ai {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.chat = this.chat.bind(this)
            this.checkTape = this.checkTape.bind(this)
            this.generateDailyRecap = this.generateDailyRecap.bind(this)
            this.listConversations = this.listConversations.bind(this)
            this.getConversation = this.getConversation.bind(this)
        }

        /**
         * Main chat endpoint with Price agent
         */
        public async chat(params: RequestType<typeof api_ai_chat_chat>): Promise<ResponseType<typeof api_ai_chat_chat>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/chat`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_chat_chat>
        }

        /**
         * Market check endpoint (for "check the tape" functionality)
         */
        public async checkTape(): Promise<ResponseType<typeof api_ai_check_tape_checkTape>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/check-tape`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_check_tape_checkTape>
        }

        /**
         * Daily recap endpoint (integrates with RunDailyRecap button)
         */
        public async generateDailyRecap(): Promise<ResponseType<typeof api_ai_generate_daily_recap_generateDailyRecap>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/daily-recap`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_generate_daily_recap_generateDailyRecap>
        }

        /**
         * List conversation sessions for the user
         */
        public async listConversations(): Promise<ResponseType<typeof api_ai_list_conversations_listConversations>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/conversations`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_list_conversations_listConversations>
        }

        /**
         * Get messages for a specific conversation
         */
        public async getConversation(params: RequestType<typeof api_ai_get_conversation_getConversation>): Promise<ResponseType<typeof api_ai_get_conversation_getConversation>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                conversationId: params.conversationId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/ai/conversation`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_ai_get_conversation_getConversation>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { list as api_news_list_list } from "~backend/news/list";
import { syncNews as api_news_sync_syncNews } from "~backend/news/sync";

export namespace news {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.list = this.list.bind(this)
            this.seed = this.seed.bind(this)
            this.sync = this.sync.bind(this)
        }

        /**
         * Retrieves the latest news items ordered by publication date.
         */
        public async list(params: RequestType<typeof api_news_list_list>): Promise<ResponseType<typeof api_news_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit: params.limit === undefined ? undefined : String(params.limit),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/news`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_news_list_list>
        }

        /**
         * Creates sample news items for testing purposes.
         */
        public async seed(): Promise<void> {
            await this.baseClient.callTypedAPI(`/news/seed`, {method: "POST", body: undefined})
        }

        /**
         * Sync news from Twitter/X and FMP Economics
         * Fetches the latest posts from monitored Twitter handles and economic calendar events
         */
        public async sync(): Promise<ResponseType<typeof api_news_sync_syncNews>> {
            const resp = await this.baseClient.callTypedAPI(`/news/sync`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_news_sync_syncNews>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getPreferences as api_notifications_get_preferences_getPreferences } from "~backend/notifications/get_preferences";
import { list as api_notifications_list_list } from "~backend/notifications/list";
import { markRead as api_notifications_mark_read_markRead } from "~backend/notifications/mark_read";
import { send as api_notifications_send_send } from "~backend/notifications/send";
import { updatePreferences as api_notifications_update_preferences_updatePreferences } from "~backend/notifications/update_preferences";

export namespace notifications {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getPreferences = this.getPreferences.bind(this)
            this.list = this.list.bind(this)
            this.markRead = this.markRead.bind(this)
            this.send = this.send.bind(this)
            this.updatePreferences = this.updatePreferences.bind(this)
        }

        public async getPreferences(): Promise<ResponseType<typeof api_notifications_get_preferences_getPreferences>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/preferences`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_get_preferences_getPreferences>
        }

        public async list(): Promise<ResponseType<typeof api_notifications_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_list_list>
        }

        public async markRead(params: { notificationId: number }): Promise<ResponseType<typeof api_notifications_mark_read_markRead>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/${encodeURIComponent(params.notificationId)}/read`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_mark_read_markRead>
        }

        public async send(params: RequestType<typeof api_notifications_send_send>): Promise<ResponseType<typeof api_notifications_send_send>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/send`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_send_send>
        }

        public async updatePreferences(params: RequestType<typeof api_notifications_update_preferences_updatePreferences>): Promise<ResponseType<typeof api_notifications_update_preferences_updatePreferences>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/preferences`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notifications_update_preferences_updatePreferences>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { listAccounts as api_projectx_list_accounts_listAccounts } from "~backend/projectx/list_accounts";
import { placeOrder as api_projectx_place_order_placeOrder } from "~backend/projectx/place_order";
import { syncProjectXAccounts as api_projectx_sync_projectx_syncProjectXAccounts } from "~backend/projectx/sync_projectx";
import {
    downlinkProjectX as api_projectx_uplink_downlinkProjectX,
    uplinkProjectX as api_projectx_uplink_uplinkProjectX
} from "~backend/projectx/uplink";

export namespace projectx {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.downlinkProjectX = this.downlinkProjectX.bind(this)
            this.listAccounts = this.listAccounts.bind(this)
            this.placeOrder = this.placeOrder.bind(this)
            this.syncProjectXAccounts = this.syncProjectXAccounts.bind(this)
            this.uplinkProjectX = this.uplinkProjectX.bind(this)
        }

        public async downlinkProjectX(): Promise<ResponseType<typeof api_projectx_uplink_downlinkProjectX>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projectx/downlink`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projectx_uplink_downlinkProjectX>
        }

        public async listAccounts(): Promise<ResponseType<typeof api_projectx_list_accounts_listAccounts>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projectx/accounts`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projectx_list_accounts_listAccounts>
        }

        public async placeOrder(params: RequestType<typeof api_projectx_place_order_placeOrder>): Promise<ResponseType<typeof api_projectx_place_order_placeOrder>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projectx/order`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projectx_place_order_placeOrder>
        }

        public async syncProjectXAccounts(): Promise<ResponseType<typeof api_projectx_sync_projectx_syncProjectXAccounts>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projectx/sync`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projectx_sync_projectx_syncProjectXAccounts>
        }

        public async uplinkProjectX(): Promise<ResponseType<typeof api_projectx_uplink_uplinkProjectX>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/projectx/uplink`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_projectx_uplink_uplinkProjectX>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { closePosition as api_trading_close_position_closePosition } from "~backend/trading/close_position";
import { executeSignal as api_trading_execute_signal_executeSignal } from "~backend/trading/execute_signal";
import { fireTestTrade as api_trading_fire_test_trade_fireTestTrade } from "~backend/trading/fire_test_trade";
import { getSignals as api_trading_get_signals_getSignals } from "~backend/trading/get_signals";
import { listPositions as api_trading_list_positions_listPositions } from "~backend/trading/list_positions";
import { toggleAlgo as api_trading_toggle_algo_toggleAlgo } from "~backend/trading/toggle_algo";

export namespace trading {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.closePosition = this.closePosition.bind(this)
            this.executeSignal = this.executeSignal.bind(this)
            this.fireTestTrade = this.fireTestTrade.bind(this)
            this.getSignals = this.getSignals.bind(this)
            this.listPositions = this.listPositions.bind(this)
            this.seedPositions = this.seedPositions.bind(this)
            this.toggleAlgo = this.toggleAlgo.bind(this)
        }

        public async closePosition(params: { positionId: number }): Promise<ResponseType<typeof api_trading_close_position_closePosition>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/trading/positions/${encodeURIComponent(params.positionId)}/close`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_trading_close_position_closePosition>
        }

        public async executeSignal(params: RequestType<typeof api_trading_execute_signal_executeSignal>): Promise<ResponseType<typeof api_trading_execute_signal_executeSignal>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/trading/execute`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_trading_execute_signal_executeSignal>
        }

        public async fireTestTrade(params: RequestType<typeof api_trading_fire_test_trade_fireTestTrade>): Promise<ResponseType<typeof api_trading_fire_test_trade_fireTestTrade>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/trading/test-trade`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_trading_fire_test_trade_fireTestTrade>
        }

        public async getSignals(): Promise<ResponseType<typeof api_trading_get_signals_getSignals>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/trading/signals`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_trading_get_signals_getSignals>
        }

        public async listPositions(): Promise<ResponseType<typeof api_trading_list_positions_listPositions>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/trading/positions`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_trading_list_positions_listPositions>
        }

        /**
         * Creates sample positions for testing purposes.
         */
        public async seedPositions(): Promise<void> {
            await this.baseClient.callTypedAPI(`/trading/seed`, {method: "POST", body: undefined})
        }

        public async toggleAlgo(params: RequestType<typeof api_trading_toggle_algo_toggleAlgo>): Promise<ResponseType<typeof api_trading_toggle_algo_toggleAlgo>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/trading/algo/toggle`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_trading_toggle_algo_toggleAlgo>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_auth>
  | Promise<RequestType<typeof auth_auth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.51.6)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_auth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
