// [claude-code 2026-03-06] Skill prompt prefixes for OpenClaw agent
// [claude-code 2026-03-11] Added prefixes for suggestion chip skills: mdb_report, tott, psych_eval, blindspots
export const SKILL_PREFIXES: Record<string, string> = {
  brief: '[SKILL:BRIEF] Search the web for the latest information about the instrument mentioned, summarize findings, and interpret what it means for the user\'s position or thesis. Check active trading regimes for timing context. Be concise and actionable.',
  validate: '[SKILL:VALIDATE] Act as Horace (risk validation). Analyze the validity of the user\'s thesis against: (1) current research narratives we\'re tracking, (2) memos we\'ve published, (3) current news via web search, (4) check active trading regimes for timing context. Assess market risk and provide a confidence-weighted verdict.',
  report: '[SKILL:REPORT] Generate an HTML dashboard report. Use the Solvys Gold palette (#D4AF37 accent, #050402 bg, #f0ead6 text). The report should be self-contained HTML with <!-- PULSE_REPORT --> as the first comment. Include inline CSS. Make it visually polished.',
  track: '[SKILL:TRACK] Start building a new narrative thread. Identify the key thesis, relevant instruments, catalysts, and timeline. Format as a structured narrative entry suitable for a sprint board.',
  psych_assist: '[SKILL:PSYCH] Run psychological/performance analysis. Evaluate trading behavior patterns, emotional state indicators, decision quality, and provide actionable coaching. Be empathetic but direct.',
  maintenance: '[SKILL:MAINTENANCE] Perform app maintenance. Review recent changes, update changelog, and report status. Format updates as structured status messages.',
  quick_pulse: '[SKILL:QUICKPULSE] Analyze the provided chart/screenshot. Provide: Bias (Bullish/Bearish/Neutral), Confidence %, Rationale, Entry 1, Entry 2, Stop Loss, Target. Be concise and actionable like a SnapTrader.',
  narrative: '[SKILL:NARRATIVE] Analyze the current NarrativeFlow board state. Identify active narratives, recent catalysts, and suggest new connections or flag stale theses. Provide structured output for narrative health assessment.',
  mdb_report: '[SKILL:MDB_REPORT] Generate a comprehensive Morning Daily Brief (MDB) report. Search the web for latest market news, check active regimes, review overnight price action. Use this exact format:\n\n**Day Type:** [Macro/Catalyst/Drift/Compounding] — one-line reason\n**Key Prints & Speeches (ET):** Each with time, actual vs expected, bullish/bearish read\n**After-Hours Movers:** Top movers with % change and implied NQ/ES point impact\n**Macro/Political Take:** 2-3 sentences — labor, inflation, geopolitical, Fed stance\n**Pressure Summary:** Current price action, key levels, consolidation vs breakout read\n**Market Risks & VIX:** Event risk status, VIX level/direction, sizing implications\n**Overall Sentiment:** One punchy sentence\n**Best Intraday Approach:** Specific strategy (Ripper, AWV, Snipe, etc.)\n\nBe direct, use financial shorthand. Anchor ONLY to key macro events. No scattergun. 400-600 words.',
  tott: '[SKILL:TOTT] Generate the Tale of the Tape — comprehensive weekly summary.\n\n**Past Week Recap:**\n- Market Overview (S&P, Nasdaq, equal-weight, sector rotation)\n- Top 3 & Bottom 3 S&P 500 Performers ($200B+ market cap) with headlines\n- NQ Futures Daily % Change for each trading day\n- Key Macro Data released with impact assessment\n- Political Commentary (administration figures, policy moves)\n- VIX Levels (weekly range and trend)\n- Sentiment summary\n\n**Upcoming Week Preview:**\n- Scheduled Events with VolScore (1-10), Forecast, Prior, NQ Reaction expectation, Priced In assessment\n- Key earnings to watch with expected impact\n- Sentiment outlook and recommended approach\n\nBe analytical, direct, use financial shorthand. 600-1000 words.',
  psych_eval: '[SKILL:PSYCH_EVAL] Run a full psychological and performance evaluation. Analyze recent trading behavior patterns, emotional state indicators from ER history, decision quality metrics, win/loss streaks, and discipline infractions. Provide actionable coaching recommendations. Be empathetic but direct.',
  blindspots: '[SKILL:BLINDSPOTS] Update and review the trader\'s blindspot analysis. Identify areas of risk, bias, or market exposure that may be overlooked. Check active narratives, current positions, and recent trade patterns for gaps in coverage or awareness. Provide specific, actionable findings.',
  regimes: '[SKILL:REGIMES] You are the Regime Tracker agent. Handle all regime-related requests: creating new trading regimes, removing regimes, analyzing regime performance, or suggesting regime adjustments based on market conditions. When creating a new regime, gather: name, description, category (institutional/session/report/custom), time range (start/end in ET), days active, bias (long/short/fade/neutral), confidence (0-100), and instruments. When removing, confirm which regime to delete. When analyzing, review ORB direction data and suggest confidence adjustments. Output structured regime data the user can review before saving.',
};
